version: '3.7'

services:
    kantoku:
        image: ghcr.io/mixtape-bot/kantoku
        container_name: kantoku
        networks:
            - nats
        volumes:
            - ./kantoku.toml:/opt/kantoku/kantoku.toml
        restart: unless-stopped
        depends_on:
            - nats
        expose:
            - 80
    nats:
        image: nats:alpine
        container_name: nats
        restart: unless-stopped
        expose:
            - 4222
        networks:
            - nats

networks:
    nats:
        name: nats
