[kantoku]
public_key = ""
publish-content-type = "application/json"
expose-test-route = false

    [kantoku.server]
    host = "127.0.0.1"
    port = 80
    prefork = true

    [kantoku.amqp]
    uri = "amqp://localhost:5672"
    group = "gateway"
    event = "INTERACTION_CREATE"

    [kantoku.logging]
    time_format = "01-02-06 15:04:05"
    timezone = "America/Los_Angeles"
