[kantoku]
public_key = ""

    [kantoku.server]
    host = "127.0.0.1"
    port = 80
    expose_test_route = false

    [kantoku.nats]
    uri = "nats://localhost:4222"
    subject = "gateway.INTERACTION_CREATE"
    no_responders = { type = 4, data = { content = "this command no workery" } }

    [kantoku.logging]
    time_format = "01-02-06 15:04:05"
    timezone = "America/Los_Angeles"
    level = "trace"
