[kantoku]
public_key = ""
publish_content_type = "application/json"

    [kantoku.server]
    host = "127.0.0.1"
    port = 80
    expose_test_route = false

    [kantoku.amqp]
    uri = "amqp://localhost:5672"
    group = "gateway"
    event = "INTERACTION_CREATE"

    [kantoku.logging]
    time_format = "01-02-06 15:04:05"
    timezone = "America/Los_Angeles"
