[kantoku]
public_key = ""
content-type = "application/msgpack"
expose-test-route = false

    [kantoku.server]
    host = "127.0.0.1"
    port = 3030
    prefork = true

    [kantoku.amqp]
    uri = "amqp://localhost:5672"
    exchange = "gateway"

    [kantoku.logging]
    time_format = "01-02-06 15:04:05"
    timezone = "America/Los_Angeles"
